/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica6;

import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Dario Trombetta y Piotr Pietruszynky
 */
public class Prct6 extends javax.swing.JFrame {

    /**
     * Creates new form Prct6
     */
    JFileChooser fc = new JFileChooser();
    FileNameExtensionFilter filter = null;
    public Prct6() {
        initComponents();
        this.setLayout(new BorderLayout(0,0));
        this.add(lienzo1,BorderLayout.CENTER );
        filter = new FileNameExtensionFilter("Text", "txt");
        fc.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("Images", "jpg", "jpeg","png");
        fc.addChoosableFileFilter(filter);
        jPanel1.setVisible(false);
        this.setTitle("Image Thresholder");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo1 = new com.mycompany.practica6.Lienzo();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        close = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        smooth = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lienzo1.setMaximumSize(new java.awt.Dimension(1024, 768));
        lienzo1.setMinimumSize(new java.awt.Dimension(0, 0));
        lienzo1.setPreferredSize(new java.awt.Dimension(330, 330));

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        jPanel1.setMinimumSize(new java.awt.Dimension(203, 152));

        jButton1.setText("Okey");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Hola y bienvenido al progrma de umbralización de Juan Auserón Delgado y de Federico Colleluori\n\nAquí les explicaremos como funciona la app y sus utilidades.\n\nEsta app tiene como objetivo darle la posibilidad al usuario de abrir una imagen de un tamaño máximo de 1024x768, umbralizarla y guardarla en su equipo.\n\nOpciones para el usuario:\n\nOpen file: Abre un archivo dentro de los archivos de tu equipo. Si el archivo seleccionado es una foto, la app la mostrará en el programa.\n\nSave file: Guarda el archivo mostrado en la app. Si no se cambia ni el nombre ni la extension del archivo, preguntará si quiere sobreescribirlo. Una vez confirmado, se guardará el nuevo archivo.\n\nClose file: Cierra el archivo sin guardar ningun tipo de cambio\n\nExit: Cierra la app.\n\nThreshold file: Umbraliza la imagen con el numero pedido al usuario como unbral. Seleccione un valor entre el 0 y el 255. Siendo un número más cercano al 0, la imagen resultante será mas \"blanca\" y cuanto más cercano al 255, la imagen resultante será mas \"negra\"");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        open.setText("Open file");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jMenu1.add(open);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        save.setText("Save file");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jMenu1.add(save);

        close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        close.setText("Close file");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jMenu1.add(close);
        jMenu1.add(jSeparator1);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('E');
        jMenu2.setText("Edit");

        smooth.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        smooth.setText("Threshold Image");
        smooth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smoothActionPerformed(evt);
            }
        });
        jMenu2.add(smooth);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('H');
        jMenu3.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("About...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        if(lienzo1.imageNull()){
            JOptionPane.showMessageDialog(rootPane, "No image has been selected", "ERROR", JOptionPane.ERROR_MESSAGE); 
        }else{
            int res = JOptionPane.showConfirmDialog(rootPane, "Close image?", "Close image", JOptionPane.YES_NO_OPTION);
            if(res == JOptionPane.YES_OPTION){
                lienzo1.exit();
            }
        }
    }//GEN-LAST:event_closeActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            lienzo1.setFile(file);
            lienzo1.setPreferredSize(lienzo1.getPreferredSize());
            pack();
        }
        if(res == JFileChooser.CANCEL_OPTION){
            
        }
    }//GEN-LAST:event_openActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if(lienzo1.imageNull()){
            JOptionPane.showMessageDialog(rootPane, "No image has been selected", "ERROR", JOptionPane.ERROR_MESSAGE);            
        }else{
            int res = fc.showSaveDialog(null);
            if (res == JFileChooser.APPROVE_OPTION){
                File file = fc.getSelectedFile();
                int res2 = JOptionPane.showConfirmDialog(rootPane, "Save file?", "Save file", JOptionPane.YES_NO_OPTION);
                if(res2 == JOptionPane.YES_OPTION){
                    if(file.exists()){
                    int res3 = JOptionPane.showConfirmDialog(rootPane, "File already exists, overwrite file?", "Overwrite file", JOptionPane.YES_NO_OPTION);
                        if(res3 == JOptionPane.YES_OPTION){
                            try {
                                lienzo1.save(file);
                            } catch (IOException ex) {
                                Logger.getLogger(Prct6.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                    try {
                        lienzo1.save(file);
                    } catch (IOException ex) {
                        Logger.getLogger(Prct6.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }      
        }
    }//GEN-LAST:event_saveActionPerformed

    private void smoothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smoothActionPerformed
        if(lienzo1.imageNull()){
            JOptionPane.showMessageDialog(rootPane, "No image has been selected", "ERROR", JOptionPane.ERROR_MESSAGE);            
        }else{
            String threshold = JOptionPane.showInputDialog("Enter threshold value between 0 and 255");
            if(threshold.matches("[0-9]+")){
                lienzo1.Threshold(Integer.parseInt(threshold));
                JOptionPane.showMessageDialog(rootPane, "Threshold process finished", "Thresholding finished", JOptionPane.INFORMATION_MESSAGE);
                repaint();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Enter a valid number with no spaces", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_smoothActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int res = JOptionPane.showConfirmDialog(rootPane, "Exit application?", "Exit", JOptionPane.YES_NO_OPTION);
           if(res == JOptionPane.YES_OPTION){
               System.exit(0);
           }if(res == JFileChooser.CANCEL_OPTION){
            
        }
    }//GEN-LAST:event_exitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prct6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prct6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prct6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prct6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prct6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem close;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private com.mycompany.practica6.Lienzo lienzo1;
    private javax.swing.JMenuItem open;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem smooth;
    // End of variables declaration//GEN-END:variables
}
